### ISSUE TITLE
upcoming / past error

### ISSUE THREAD

**Issue by ligi** [wslyvh/show-up#3]
upcoming and past events show the same content - unless I missed that we are in the singularity now I would consider this a bug

![image](https://github.com/wslyvh/show-up/assets/111600/010032a7-bc36-4e4d-afcf-04ba50f2ee01)

![image](https://github.com/wslyvh/show-up/assets/111600/3e11ac73-38f4-470d-b600-c0145dfc4d0e)

**Comment by wslyvh** [comment]
Fixed
