### ISSUE TITLE
Bad state after event creation tx was send

### ISSUE THREAD

**Issue by ligi** [wslyvh/show-up#4]
After I clicked on "create event" and submitted the transaction I end up in this state:

![image](https://github.com/wslyvh/show-up/assets/111600/b40c8a32-e7d8-4765-8b6d-715eeb864d91)

which feels like I would create the event again.
Feels like I should end up in some pending state until the event is indexed.

Also the tx is now already more than 10 minutes ago - so it should be indexed already - so maybe something else is going wrong there also:

https://optimistic.etherscan.io/tx/0x8ea878cc6faa84ff9ded4f6affdd642c74486e6153ac4d46d31a2834766c0027

**Comment by wslyvh** [comment]
Agree on better feedback and pending states. There's a lot that can be improved there. It requires a bit more work tho.

In the meantime, I've updated the text that it can take up to 30 mins.

**Comment by wslyvh** [comment]
Fixed an issue where the transaction notification failed after creating the event.
I think this prevented further feedback and status/UX updates.

![image](https://github.com/wslyvh/show-up/assets/25974464/7dc59728-6ea1-44e0-8762-78a312701032)
