### ISSUE TITLE
connected/disconnected with Zerion

### ISSUE THREAD

**Issue by ligi** [wslyvh/show-up#6]
Might also be something with zerion - but also weird that it detects a connection in one page but not in the other. Feel free to close if it is a zerion bug

https://github.com/wslyvh/show-up/assets/111600/3cd62197-91ff-445a-8897-5a1ab7687f72

**Comment by wslyvh** [comment]
The "Not connected" error is a fallback when you try to perform an action without being connected. The UI should've prevented that to happen in the first place though. Are you able to reproduce this? I.e. do you remember the steps you took before what's being recorded?

**Comment by ligi** [comment]
It was kinda the normal steps before - but do not recall 100% - but it was reproducible. 
Just tried it again - got a bit further - but still a bit weird behavior:


https://github.com/wslyvh/show-up/assets/111600/c39046ec-8ac2-4eb7-a6d0-1edc6febbc7c

**Comment by wslyvh** [comment]
I think the approval/register issue was similar to the bug on #4 so should be fixed

I did notice there is still some delay in updating the UI (cache) which can make it seem like nothing happened.

**Comment by wslyvh** [comment]
I think this should be fixed now. 
There was indeed a mismatch between server side vs. client-side cache.
Invalidating both now on any user action

Also FYI - you can play around on Sepolia as well https://test.showup.events/
