### ISSUE TITLE
Bug Report 🐞

### ISSUE THREAD

**Issue by yaronski** [wslyvh/show-up#7]
## Description
Next.js app break down with error `FUNCTION_INVOCATION_TIMEOUT` after successful registration for [https://www.showup.events/events/2](https://www.showup.events/events/2).

## Course of events
Setting the DAI allowance and propagating the registration transaction to the wallet extension and network worked flawlessly.
[https://optimistic.etherscan.io/tx/0x5a31980a8741426a17cf5062d2ea7ea13e42b90794f70d52d2b904f424eaf289](https://optimistic.etherscan.io/tx/0x5a31980a8741426a17cf5062d2ea7ea13e42b90794f70d52d2b904f424eaf289) The `register` contract interaction was successful.
However the Next.js app broke down.

## Screenshots

![A6aKkN92xh](https://github.com/wslyvh/show-up/assets/10449672/2fd46bc1-75a7-4469-a0c8-575c81580e6a)

![1YWh5xVpch](https://github.com/wslyvh/show-up/assets/10449672/acc4e6f7-d2ed-46ae-b9c2-2aeb57a9c8c9)

![fKFwKFRzYh](https://github.com/wslyvh/show-up/assets/10449672/4f1c7d34-5530-4e46-aadb-20cfd99f1c1b)

![nyVZp7CANF](https://github.com/wslyvh/show-up/assets/10449672/4593f445-22d1-4667-85d6-b78a92855957)

![8OwcHroj5w](https://github.com/wslyvh/show-up/assets/10449672/45c362b7-90fb-4223-954d-05b4c929a269)

## OS / Applications
 - Windows 11 Pro (64-Bit)
 - Firefox 120.0.1 (64-Bit)
 - MM v.11.6.2

**Comment by wslyvh** [comment]
Thanks for the detailed report! Seems like it had something to do with fetching ENS Profiles, which was causing a timeout on Vercel. I temporarily disabled ENS profiles for now, as I'm working on another indexer actually that would improve that anyway.
